/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /home/daffy/u0/vern/flex/RCS/flex.skl,v 2.91 96/09/10 16:58:48 vern Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#include <unistd.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *yy_str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)


#define yywrap() 1
#define YY_SKIP_YYWRAP
typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 19
#define YY_END_OF_BUFFER 20
static yyconst short int yy_accept[192] =
    {   0,
        0,    0,   20,   18,   17,   11,   18,   12,   11,   11,
       18,   12,   11,   11,   11,   12,   11,    2,    1,   11,
       11,   11,   18,   10,   11,   10,   10,   10,   10,   10,
       10,   10,   10,   10,   10,   10,   10,   10,   10,   10,
       11,   11,   11,    0,    6,    0,    0,    0,    0,    5,
        0,    4,    0,   14,    4,    2,    4,    0,    0,    1,
       11,   11,   10,   10,   10,   10,   10,   10,   10,    8,
       10,   10,   10,   10,   10,   10,    8,   10,   10,   10,
       10,   10,   10,   10,   10,   10,   10,   10,    0,    0,
        5,   12,    0,    0,    0,   14,   14,    0,    4,    3,

       10,   10,   10,   10,   10,   10,   10,   10,   10,   10,
       10,   10,    7,   10,   10,   10,   10,   10,   10,   10,
       10,   10,   10,   10,   10,   10,   10,   10,    0,    0,
       13,   14,   14,    9,   10,   10,   10,   10,   10,   10,
       10,   10,   10,   10,   10,   10,   10,   10,   10,   10,
       10,   10,   10,   10,    0,    0,   10,   10,   10,   10,
       10,   10,   10,   10,   10,   10,   10,   10,   10,   10,
        0,    0,   10,   10,   10,   10,   10,   10,    0,    0,
       10,   10,   10,   10,    0,    0,   15,    0,   15,   16,
        0

    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    2,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    3,    4,    5,    6,    1,    7,    8,    9,   10,
       10,   11,   12,   13,   14,   15,   16,   17,   18,   18,
       18,   18,   18,   18,   18,   19,   19,   20,   13,   21,
       22,   23,   24,    1,   25,   25,   25,   25,   26,   25,
       27,   27,   27,   27,   27,   27,   27,   27,   27,   27,
       27,   27,   27,   27,   27,   27,   27,   28,   27,   27,
       13,   29,   13,   30,   31,    1,   32,   33,   34,   35,

       36,   37,   38,   39,   40,   27,   41,   42,   43,   44,
       45,   46,   27,   47,   48,   49,   50,   51,   52,   53,
       54,   55,   13,   56,   13,   57,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[58] =
    {   0,
        1,    2,    1,    1,    1,    1,    1,    1,    1,    3,
        1,    1,    1,    1,    1,    4,    5,    5,    5,    1,
        1,    1,    1,    1,    6,    6,    7,    7,    1,    1,
        7,    6,    6,    6,    6,    6,    6,    7,    7,    7,
        7,    7,    7,    7,    7,    7,    7,    7,    7,    7,
        7,    7,    7,    7,    7,    3,    1
    } ;

static yyconst short int yy_base[201] =
    {   0,
        0,    0,  343,  344,  344,   54,   54,   25,  320,   53,
      332,  344,  318,   50,   55,   49,   63,   69,   74,   49,
      317,  315,  317,    0,  314,  285,  287,   62,   37,   60,
       54,  288,   71,  287,  295,   72,  276,  285,  283,  288,
       58,  344,  344,   98,  344,   53,  290,  281,  315,  314,
      307,   99,  108,  292,  112,  124,  136,  147,    0,  152,
      298,  297,    0,  269,  281,  268,  283,  270,  276,  262,
      263,  260,  260,  263,  260,  257,    0,  256,  260,   85,
      258,   43,  100,  262,  255,   80,  104,  260,  262,  264,
      344,  344,  129,  281,  147,  267,  266,  156,  162,    0,

      249,  261,  256,  244,  108,  258,  256,  252,  244,  250,
      253,  239,    0,  245,  242,  231,  233,  235,  242,  228,
      226,  226,  238,  228,  232,  236,  238,  227,  228,  225,
      344,  237,  236,    0,  223,  214,  222,  211,  218,  212,
      209,  209,  209,  206,  218,  208,  212,  217,  216,  214,
      204,  209,  197,  209,  200,  193,  198,  199,  204,  195,
      189,  193,  201,  198,  200,  174,  175,  173,  153,  151,
      154,  152,  136,  136,  148,  146,  146,  135,  173,  132,
      116,   98,  101,   97,    0,  123,    0,   85,    0,  344,
      344,  188,  195,  198,  205,  212,  215,  221,  223,  226

    } ;

static yyconst short int yy_def[201] =
    {   0,
      191,    1,  191,  191,  191,  191,  192,  191,  191,  191,
      193,  191,  191,  191,  191,  191,  191,  191,  191,  191,
      191,  191,  191,  194,  191,  194,  194,  194,  194,  194,
      194,  194,  194,  194,  194,  194,  194,  194,  194,  194,
      191,  191,  191,  192,  191,  192,  191,  191,  191,  191,
      191,  191,  195,  196,  191,  191,  191,  191,  197,  191,
      191,  191,  194,  194,  194,  194,  194,  194,  194,  194,
      194,  194,  194,  194,  194,  194,  194,  194,  194,  194,
      194,  194,  194,  194,  194,  194,  194,  194,  191,  191,
      191,  191,  195,  191,  195,  196,  198,  191,  191,  197,

      194,  194,  194,  194,  194,  194,  194,  194,  194,  194,
      194,  194,  194,  194,  194,  194,  194,  194,  194,  194,
      194,  194,  194,  194,  194,  194,  194,  194,  191,  191,
      191,  196,  198,  194,  194,  194,  194,  194,  194,  194,
      194,  194,  194,  194,  194,  194,  194,  194,  194,  194,
      194,  194,  194,  194,  191,  191,  194,  194,  194,  194,
      194,  194,  194,  194,  194,  194,  194,  194,  194,  194,
      191,  191,  194,  194,  194,  194,  194,  194,  191,  191,
      194,  194,  194,  194,  199,  191,  200,  191,  200,  191,
        0,  191,  191,  191,  191,  191,  191,  191,  191,  191

    } ;

static yyconst short int yy_nxt[402] =
    {   0,
        4,    5,    4,    6,    7,    8,    9,   10,   11,   12,
       13,   14,   12,   15,   16,   17,   18,   19,   19,   12,
       20,   21,   22,   23,   24,   24,   24,   24,    4,   25,
       24,   26,   27,   28,   29,   30,   31,   32,   24,   33,
       24,   34,   24,   24,   24,   24,   35,   36,   37,   38,
       39,   40,   24,   24,   24,   41,   42,   43,   45,   47,
       43,   43,   44,   51,   48,   52,   52,   52,   43,   61,
       43,   43,   69,   53,   43,   43,   43,   43,   54,   43,
      118,   70,   46,   55,   43,   56,   56,   57,   55,  190,
       60,   60,   60,   66,   58,   74,   59,  119,   75,   58,

       67,   71,   45,   72,   58,  190,   68,   77,   44,   58,
       81,   82,   73,   43,   78,   52,   52,   52,   94,  124,
       83,   59,  115,   84,   58,  188,   46,  125,   52,   52,
       52,  120,  134,  116,   58,  113,   95,   58,   55,   94,
       56,   56,   57,  126,  134,  127,  121,   58,  191,   58,
       55,   77,   57,   57,   57,  136,  137,   95,   98,   58,
       98,   58,   93,   99,   99,   99,   55,  186,   60,   60,
       60,   58,   99,   99,   99,  185,  184,   58,   99,   99,
       99,  183,  134,  182,  134,  181,  180,   58,   44,  179,
      178,   44,   44,   44,   44,   49,  177,   49,   49,   49,

       49,   49,   63,   63,   63,   93,   93,   93,  176,   93,
       93,   93,   96,   77,   96,   96,   96,   96,   96,  100,
      100,  132,  113,  132,  132,  132,  132,  132,  187,  187,
      189,  189,  189,  134,  134,  113,   77,  175,  134,  113,
      174,  173,  172,  171,   77,  170,  169,  113,  168,  167,
      166,  165,  164,  163,  113,  162,  161,  113,  160,  159,
      158,  157,  134,   77,  133,   97,  156,  155,  154,  153,
      113,  152,  151,  150,  149,  148,  147,  146,  145,  144,
      143,  142,  113,   77,  141,  140,  113,   77,  139,  138,
      113,   77,  135,  134,  133,   97,  131,  130,  129,  128,

      123,  122,  117,  114,  113,  112,   77,  111,  110,  109,
      108,  107,  106,  105,  104,  103,  102,  101,   43,   43,
       97,   92,   91,   91,   90,   89,   88,   87,   86,   85,
       80,   79,   76,   65,   64,   43,   43,   62,   43,   43,
       50,   43,  191,    3,  191,  191,  191,  191,  191,  191,
      191,  191,  191,  191,  191,  191,  191,  191,  191,  191,
      191,  191,  191,  191,  191,  191,  191,  191,  191,  191,
      191,  191,  191,  191,  191,  191,  191,  191,  191,  191,
      191,  191,  191,  191,  191,  191,  191,  191,  191,  191,
      191,  191,  191,  191,  191,  191,  191,  191,  191,  191,

      191
    } ;

static yyconst short int yy_chk[402] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    6,    7,    8,
       10,   14,   46,   16,    8,   16,   16,   16,   15,   20,
       20,   14,   29,   17,   10,    6,   15,   15,   17,   41,
       82,   29,    7,   18,   17,   18,   18,   18,   19,  188,
       19,   19,   19,   28,   18,   31,   18,   82,   31,   19,

       28,   30,   44,   30,   18,  188,   28,   33,   46,   19,
       36,   36,   30,   41,   33,   52,   52,   52,   53,   86,
       36,   18,   80,   36,   52,  186,   44,   86,   55,   55,
       55,   83,  184,   80,   52,  183,   53,   55,   56,   93,
       56,   56,   56,   87,  182,   87,   83,   55,   95,   56,
       57,  181,   57,   57,   57,  105,  105,   93,   58,   56,
       58,   57,   95,   58,   58,   58,   60,  180,   60,   60,
       60,   57,   98,   98,   98,  179,  178,   60,   99,   99,
       99,  177,  176,  175,  174,  173,  172,   60,  192,  171,
      170,  192,  192,  192,  192,  193,  169,  193,  193,  193,

      193,  193,  194,  194,  194,  195,  195,  195,  168,  195,
      195,  195,  196,  167,  196,  196,  196,  196,  196,  197,
      197,  198,  166,  198,  198,  198,  198,  198,  199,  199,
      200,  200,  200,  165,  164,  163,  162,  161,  160,  159,
      158,  157,  156,  155,  154,  153,  152,  151,  150,  149,
      148,  147,  146,  145,  144,  143,  142,  141,  140,  139,
      138,  137,  136,  135,  133,  132,  130,  129,  128,  127,
      126,  125,  124,  123,  122,  121,  120,  119,  118,  117,
      116,  115,  114,  112,  111,  110,  109,  108,  107,  106,
      104,  103,  102,  101,   97,   96,   94,   90,   89,   88,

       85,   84,   81,   79,   78,   76,   75,   74,   73,   72,
       71,   70,   69,   68,   67,   66,   65,   64,   62,   61,
       54,   51,   50,   49,   48,   47,   40,   39,   38,   37,
       35,   34,   32,   27,   26,   25,   23,   22,   21,   13,
       11,    9,    3,  191,  191,  191,  191,  191,  191,  191,
      191,  191,  191,  191,  191,  191,  191,  191,  191,  191,
      191,  191,  191,  191,  191,  191,  191,  191,  191,  191,
      191,  191,  191,  191,  191,  191,  191,  191,  191,  191,
      191,  191,  191,  191,  191,  191,  191,  191,  191,  191,
      191,  191,  191,  191,  191,  191,  191,  191,  191,  191,

      191
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "TP3.l"
#define INITIAL 0
#line 4 "TP3.l"
// Definicion de las librerías que incluímos
#include <stdio.h>
#include <string.h> // strcpy, strcmp
#include <ctype.h>  // toupper y isdigit
#include <math.h>   // pow
#include <stdlib.h> // atoi, atof

// Deficinion de directivas de preprocesamiento
#define DECIMAL 0
#define OCTAL 1
#define HEXADECIMAL 2
#define CARACTER 3
#define REAL 4
#define LITERAL_CADENA 5
#define P_RESERVADA 6
#define IDENTIFICADOR 7
#define OPERADOR 8
#define PUNTUACION 9
#define COMENTARIO 10
#define DEFINE 11 
#define INCLUDE 12
#define NO_RECONOCIDOS 13

#define BASE8 8
#define BASE16 16


// Definicion de estructuras
typedef struct nodo{
    char nombre[32];    /* asumimos un tamaño para el identificador de 31 caracteres + '\0' = 32 */
    int cantidad;
    char categoria[20];
    struct nodo* sgte;
} Nodo;

struct infoCola{
    char nombre[101];    /* asumimos un tamaño para el literal cadena y de los comentarios de 100 caracteres + '\0' + " + " = 101 */
    int cantidad;
    char categoria[32];
} ;

typedef struct nodoCola{
    struct infoCola info;
    struct nodoCola* sgte;
} NodoCola;


struct cola {
    NodoCola* primero;
	NodoCola* ultimo;
} typedef tipoCola;


// Definicion de Variables Globales
Nodo* listaIdentificadores;
Nodo* listaOper_CarPunt;

tipoCola* LiteralCadena;
tipoCola* PalabrasReservadas;
tipoCola* decimales;
tipoCola* octales;
tipoCola* hexadecimales;
tipoCola* reales;
tipoCola* caracteres;
tipoCola* comentarios;
tipoCola* NoReconocidos;

int ACUMULADOR_DECIMALES = 0, CONTADOR_CARACTERES = 0, CONTADOR_SALTOS_DE_LINEA = 1, CONTADOR_DEFINE = 0, CONTADOR_INCLUDE = 0;
FILE* arcFinal;

/* Prototipo de FUNCIONES*/
int buscarCadena(Nodo*, char*);
void insertarPrimeroIdentificador(char*);
void insertarEnMedioIdentificador(char*);
void insertarOrdenadoIdentificador(char*);
void insertarLiteralCadena(char*, int);
void insertarOperador_Puntuacion(char*, char*);
void modificarNodo(Nodo*, char*);
void cargarSinRepetir(Nodo*, char*, int);
tipoCola* crearCola();
void encolar(tipoCola*, char*, int, char*);
struct infoCola desencolar(tipoCola*);
int caracterHexadecimalADecimal(char);
int convertirAdecimal(char*, int, int);
int contieneSaltoDeLinea(char*, int);

void imprimirLista(Nodo*, FILE*, int);
void imprimirCola(tipoCola*, FILE*, int);

void imprimirIdentificadores(FILE*);
void imprimirLiteralesCadena(FILE*);
void imprimirPalabrasReservadas(FILE*);
void imprimirConstantes(FILE*);
void imprimirOper_Y_CarPunt(FILE*);
void imprimirComentarios(FILE*);
void imprimirNoReconocidos(FILE*);
void imprimirDirectivasPrecompilador(FILE*);


#line 622 "lex.yy.c"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;

#line 113 "TP3.l"


#line 776 "lex.yy.c"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				yy_last_accepting_state = yy_current_state;
				yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 192 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 344 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;


do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yy_hold_char;
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 115 "TP3.l"
{ACUMULADOR_DECIMALES += atoi(yytext); encolar(decimales, yytext, 0, "Decimal");}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 116 "TP3.l"
{ encolar(octales, yytext, convertirAdecimal(yytext, BASE8, yyleng), "Octal");}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 117 "TP3.l"
{ encolar(hexadecimales, yytext, convertirAdecimal(yytext, BASE16, yyleng), "Hexa");}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 118 "TP3.l"
{encolar(reales, yytext, atof(yytext), "Real");}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 119 "TP3.l"
{encolar(caracteres, yytext, (CONTADOR_CARACTERES += 1), "Caracter");}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 121 "TP3.l"
{ encolar(LiteralCadena, yytext, yyleng - 2, "");} 
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 123 "TP3.l"
{ encolar(PalabrasReservadas, yytext, 0, "Tipo de Dato");}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 124 "TP3.l"
{ encolar(PalabrasReservadas, yytext, 0, "Estructura de Control");}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 125 "TP3.l"
{ encolar(PalabrasReservadas, yytext, 0, "Otros");}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 127 "TP3.l"
{cargarSinRepetir(listaIdentificadores, yytext, IDENTIFICADOR);} 
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 129 "TP3.l"
{ cargarSinRepetir(listaOper_CarPunt, yytext, OPERADOR);}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 130 "TP3.l"
{ cargarSinRepetir(listaOper_CarPunt, yytext, PUNTUACION);}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 132 "TP3.l"
{encolar(comentarios, yytext, 0, "Multiples Lineas"); contieneSaltoDeLinea(yytext, yyleng);}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 133 "TP3.l"
{encolar(comentarios, yytext, 0, "1 Linea");}
	YY_BREAK
case 15:
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */
yy_c_buf_p = yy_cp = yy_bp + 7;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 135 "TP3.l"
{CONTADOR_DEFINE += 1;}
	YY_BREAK
case 16:
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */
yy_c_buf_p = yy_cp = yy_bp + 8;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 136 "TP3.l"
{CONTADOR_INCLUDE += 1;}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 138 "TP3.l"
{encolar(NoReconocidos, "\\n", CONTADOR_SALTOS_DE_LINEA, "" ); CONTADOR_SALTOS_DE_LINEA += 1;}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 139 "TP3.l"
{encolar(NoReconocidos, yytext, CONTADOR_SALTOS_DE_LINEA, "" );}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 141 "TP3.l"
ECHO;
	YY_BREAK
#line 960 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yy_last_accepting_state = yy_current_state;
			yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 192 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;
	register char *yy_cp = yy_c_buf_p;

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yy_last_accepting_state = yy_current_state;
		yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 192 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 191);

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;


	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;


	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO(( int ));
#endif
#endif

#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *yy_str )
#else
YY_BUFFER_STATE yy_scan_string( yy_str )
yyconst char *yy_str;
#endif
	{
	int len;
	for ( len = 0; yy_str[len]; ++len )
		;

	return yy_scan_bytes( yy_str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 141 "TP3.l"


int main() {
   
    /* Acciones previas a la invocación del analizador léxico */

    yyin = fopen("entrada.txt", "r");
    yyout = fopen("salida.txt", "w");
    arcFinal = fopen ("Informe.txt", "w");

    // Inicializacion de las estructuras enlazadas
    listaIdentificadores = NULL;
    listaOper_CarPunt = NULL;

    LiteralCadena = crearCola();
    PalabrasReservadas = crearCola();
    decimales = crearCola();
    octales = crearCola();
    hexadecimales = crearCola();
    caracteres = crearCola ();
    reales = crearCola();
    comentarios = crearCola();
    NoReconocidos = crearCola();

    /* Invocación del analizador léxico */
    yylex();

    /* Acciónes posteriores a la ejecución del analizador léxico */

    fprintf(arcFinal, "                             INFORME - FLEX para reconocimiento de categorías léxicas de C                               \n\n");
    fprintf(arcFinal, "-------------------------------------------------------------------------------------------------------------------------\n\n");
    imprimirIdentificadores(arcFinal);
    imprimirLiteralesCadena(arcFinal);
    imprimirPalabrasReservadas(arcFinal);
    imprimirConstantes(arcFinal);
    imprimirOper_Y_CarPunt(arcFinal);
    imprimirComentarios(arcFinal);
    imprimirNoReconocidos(arcFinal);
    imprimirDirectivasPrecompilador(arcFinal);

	fclose(arcFinal);

    return 0;
}

int buscarCadena(Nodo* lista, char* cadena){
    Nodo* actual = lista;

    while(actual != NULL && (strcmp(cadena, actual->nombre) != 0))
        actual = actual->sgte;

    if(actual != NULL && (strcmp(cadena, actual->nombre) == 0))
        return 1;
	else
        return 0;
}

void insertarPrimeroIdentificador(char* identificador){
    Nodo* nuevoNodo = (Nodo*) malloc(sizeof(Nodo));
    strcpy (nuevoNodo->nombre, identificador);
    nuevoNodo->cantidad = 1; 
    nuevoNodo->sgte = listaIdentificadores; 
    listaIdentificadores = nuevoNodo; 
}

void insertarEnMedioIdentificador(char* identificador){
    Nodo* nuevoNodo = (Nodo*) malloc(sizeof(Nodo)); 
    Nodo*aux = listaIdentificadores; 
    strcpy (nuevoNodo->nombre, identificador);
    nuevoNodo->cantidad = 1; 

    while(aux->sgte != NULL && (strcmp(identificador, aux->sgte->nombre) > 0)){ 
        aux = aux->sgte; 
    } 
    nuevoNodo->sgte = aux->sgte; 
    aux->sgte = nuevoNodo; 
}

void insertarOrdenadoIdentificador(char* identificador){
    if (listaIdentificadores == NULL || (strcmp(listaIdentificadores->nombre, identificador) > 0)) 
        insertarPrimeroIdentificador(identificador);
    else 
        insertarEnMedioIdentificador(identificador);
}

void insertarOperador_Puntuacion(char* cadena, char* categoria){
	Nodo* nuevoNodo = (Nodo*) malloc(sizeof(Nodo));
    strcpy (nuevoNodo->nombre, cadena);
    nuevoNodo->cantidad = 1;
    strcpy (nuevoNodo->categoria, categoria);

	if(listaOper_CarPunt == NULL){
        nuevoNodo->sgte = listaOper_CarPunt; 
        listaOper_CarPunt = nuevoNodo;
	}
    else{
        Nodo* aux = listaOper_CarPunt;

        while(aux->sgte != NULL)
            aux = aux->sgte; 
        nuevoNodo->sgte = NULL;
        aux->sgte = nuevoNodo;
	}
}

void modificarNodo(Nodo* lista, char* cadena){
	Nodo* actual = lista;
	int encontrado = 0;

	if(lista != NULL){
		while(actual != NULL && encontrado != 1){
			if(strcmp(cadena, actual->nombre) == 0){
				actual->cantidad += 1;
				encontrado = 1;
			}
            else	
			    actual = actual->sgte;
		}
	}
}

void cargarSinRepetir(Nodo* lista, char* cadena, int token){
    int aux = buscarCadena(lista, cadena);
               
    if(aux)
        modificarNodo(lista, cadena);
    else{
        switch (token){
            case IDENTIFICADOR:
                insertarOrdenadoIdentificador(cadena);
                break;
            case OPERADOR:
                insertarOperador_Puntuacion(cadena, "Operador");
                break;
            case PUNTUACION:
                insertarOperador_Puntuacion(cadena, "Puntuacion");
        }
    }
}

tipoCola* crearCola(void){
	tipoCola* cola = malloc(sizeof(tipoCola)); 
	if(cola == NULL) return NULL;
	cola->primero  =NULL;
	cola->ultimo = NULL;
	return cola;
}


void encolar(tipoCola* cola, char* cadena, int valor, char* categoria){
	NodoCola* nuevoNodo = (NodoCola*)malloc(sizeof(NodoCola));

    strcpy(nuevoNodo->info.nombre, cadena);
    nuevoNodo->info.cantidad = valor;
    strcpy(nuevoNodo->info.categoria, categoria);
	nuevoNodo->sgte = NULL;

	if (cola->primero == NULL)
		cola->primero = nuevoNodo;
	else
		cola->ultimo->sgte = nuevoNodo;
	
    cola->ultimo = nuevoNodo;	
}

struct infoCola desencolar(tipoCola *cola){
	if(cola->primero == NULL){
        fprintf(arcFinal,"\n La cola se encuentra vacia\n\n");
        cola->ultimo = NULL;
    }
    else {
        struct infoCola info;
        strcpy(info.nombre, cola->primero->info.nombre);
        info.cantidad = cola->primero->info.cantidad;
        strcpy(info.categoria, cola->primero->info.categoria); 

        NodoCola* aux = cola->primero;
        cola->primero = aux->sgte; 
        free(aux);
        return info;
    }
	
}


int caracterHexadecimalADecimal(char caracter) {
  if (isdigit(caracter))
    return caracter - '0';
  return 10 + (toupper(caracter) - 'A');
}


int convertirAdecimal(char* numeroAconvertir, int Base, int longitud) {
    int numeroDecimal = 0, potencia = 0;
    int valorActual;

    if(numeroAconvertir == "0")
        return numeroDecimal = 0;
    else {
        switch(Base){
            case BASE8:
                for(int i = longitud - 1; i >= 1; i-- ){
                    valorActual = numeroAconvertir[i] - '0';
                    numeroDecimal += valorActual * pow(Base,potencia);
                    potencia++;
                }   
                break;
            case BASE16:
                for(int i = longitud - 1; i >= 2; i-- ){
                    valorActual = caracterHexadecimalADecimal(numeroAconvertir[i]);
                    numeroDecimal += valorActual * pow(Base,potencia);
                    potencia++;
                }
                break;
        }
        return numeroDecimal;
    }
}

int contieneSaltoDeLinea(char* cadena, int longitud){
    for(int i = 0; i < longitud; i++){
        if(cadena[i] == '\n')
            CONTADOR_SALTOS_DE_LINEA += 1;
    }
}


void imprimirLista(Nodo* lista, FILE* arcFinal, int token){
    Nodo* actual = lista;

    if(lista != NULL){
        while(actual != NULL){
            switch (token){
            case IDENTIFICADOR:
                fprintf (arcFinal, "|\t%-32s\t|%15d%14s|\n", actual->nombre, actual->cantidad," ");
                break;
            case OPERADOR ... PUNTUACION:
                fprintf (arcFinal, "|\t\t %-9s\t|\t%4d\t\t|\t%-22s\t|\n", actual->nombre, actual->cantidad, actual->categoria);
                break;
            }
            actual = actual->sgte;
        }
	}
    else
		fprintf(arcFinal,"\n La lista se encuentra vacia\n\n"); 
}



void imprimirCola(tipoCola* cola, FILE* arcFinal, int categoria){
    struct infoCola info;
    

    if(cola->primero != NULL){
        while(cola->primero != NULL){
            info = desencolar(cola);
            float mantisa = atof(info.nombre);

            switch (categoria){
                case DECIMAL:
                    fprintf (arcFinal, "|%20s\t|\t%-37s\t|\n", info.nombre, info.categoria);
                    break;
                case OCTAL ... CARACTER:
                    fprintf (arcFinal, "|%20s\t|\t%8d\t|\t%-22s\t|\n", info.nombre, info.cantidad, info.categoria);
                    break;
                case REAL:
                    fprintf (arcFinal, "|%20s\t|\t%8d\t|\t%.5f\t|\t%-9s\t|\n", info.nombre, info.cantidad, mantisa - info.cantidad, info.categoria);
                    break;                                                                                 
                case LITERAL_CADENA:
                    fprintf (arcFinal, "|\t%-100s\t|\t%-4d\t |\n", info.nombre, info.cantidad);  
                    break;
                case P_RESERVADA:
                    fprintf (arcFinal, "|\t%17s\t|\t%-37s\t|\n", info.nombre, info.categoria);  
                    break;
                case COMENTARIO:
                    fprintf (arcFinal, "| %-100s | %-16s |\n", info.nombre, info.categoria);
                    break;
                case NO_RECONOCIDOS:
                    if(strcmp(info.nombre, " ")  != 0)
                        fprintf (arcFinal, "|%30s\t|\t%-30d|\n", info.nombre, info.cantidad);
                    else
                        fprintf (arcFinal, "|%30s\t|\t%-30d|\n", "espacio", info.cantidad);
                    break;
            }       
        }
	}
    else
		fprintf(arcFinal,"\n La cola se encuentra vacia\n\n");
}


void imprimirIdentificadores(FILE* arcFinal){
    fprintf(arcFinal, "_______________________________________________________________________\n");
    fprintf(arcFinal, "|                      Lista de Identificadores                       |\n");
    fprintf(arcFinal, "|_____________________________________________________________________|\n");
    fprintf(arcFinal, "|                 Lexema                |        Nro Repeticiones     |\n");
    fprintf(arcFinal, "|_______________________________________|_____________________________|\n");
    imprimirLista(listaIdentificadores, arcFinal, IDENTIFICADOR);
    
    fprintf(arcFinal, "|_______________________________________|_____________________________|\n\n");
}

void imprimirLiteralesCadena(FILE* arcFinal){
    fprintf(arcFinal, "\n\n__________________________________________________________________________________________________________________________\n");
    fprintf(arcFinal, "|                                                   Lista de literales Cadena                                            |\n");
    fprintf(arcFinal, "|________________________________________________________________________________________________________________________|\n");
    fprintf(arcFinal, "|                                                     Lexema                                                  | Longitud |\n");
    fprintf(arcFinal, "|_____________________________________________________________________________________________________________|__________|\n");

    imprimirCola(LiteralCadena, arcFinal, LITERAL_CADENA);
    fprintf(arcFinal, "|_____________________________________________________________________________________________________________|__________|\n\n");
}

void imprimirPalabrasReservadas(FILE* arcFinal){
    fprintf(arcFinal, "\n\n_______________________________________________________________________\n");
    fprintf(arcFinal, "|                    Lista de Palabras Reservadas                     |\n");
    fprintf(arcFinal, "|_____________________________________________________________________|\n");
    fprintf(arcFinal, "|             Lexema     |                 Categoria                  |\n");
    fprintf(arcFinal, "|________________________|____________________________________________|\n");

    imprimirCola(PalabrasReservadas, arcFinal, P_RESERVADA);
    fprintf(arcFinal, "|________________________|____________________________________________|\n\n");
}

void imprimirConstantes(FILE* arcFinal){
    fprintf(arcFinal, "\n\n_______________________________________________________________________\n");
    fprintf(arcFinal, "|                            Lista de Constantes                      |\n");
    fprintf(arcFinal, "|_____________________________________________________________________|\n");
    fprintf(arcFinal, "|              Lexema    |     Token                                  |\n");
    fprintf(arcFinal, "|------------------------|--------------------------------------------|\n");
    imprimirCola(decimales, arcFinal, DECIMAL);
    fprintf(arcFinal, "|          ---------------                                            |\n");
    fprintf(arcFinal, "| TOTAL \t%10d                                                  |\n|%69s|\n", ACUMULADOR_DECIMALES, " ");

    fprintf(arcFinal, "|---------------------------------------------------------------------|\n");
    fprintf(arcFinal, "|              Lexema    |  Val Decimal |     Token                   |\n");
    fprintf(arcFinal, "|------------------------|--------------|-----------------------------|\n");
    imprimirCola(octales, arcFinal, OCTAL);
    imprimirCola(hexadecimales, arcFinal, HEXADECIMAL);
    fprintf(arcFinal, "|%69s|\n", " ");

    fprintf(arcFinal, "|---------------------------------------------------------------------|\n");
    fprintf(arcFinal, "|              Lexema    | Parte Entera |    Mantisa   |    Token     |\n");
    fprintf(arcFinal, "|------------------------|--------------|--------------|--------------|\n");
    imprimirCola(reales, arcFinal, REAL);
    fprintf(arcFinal, "|%69s|\n", " ");    
    
    fprintf(arcFinal, "|---------------------------------------------------------------------|\n");
    fprintf(arcFinal, "|              Lexema    | Or aparicion |     Token                   |\n");
    fprintf(arcFinal, "|------------------------|--------------|-----------------------------|\n");
    imprimirCola(caracteres, arcFinal, CARACTER);
    
    fprintf(arcFinal, "|________________________|______________|_____________________________|\n");
}


void imprimirOper_Y_CarPunt(FILE* arcFinal){
    fprintf(arcFinal, "\n\n_______________________________________________________________________\n");
    fprintf(arcFinal, "|            Lista de Operadores y Caracteres de Puntuacion           |\n");
    fprintf(arcFinal, "|_____________________________________________________________________|\n");
    fprintf(arcFinal, "|        Lexema          | Repeticiones |     Token                   |\n");
    fprintf(arcFinal, "|________________________|______________|_____________________________|\n");
    imprimirLista(listaOper_CarPunt, arcFinal, OPERADOR);
    
    fprintf(arcFinal, "|________________________|______________|_____________________________|\n");
}

void imprimirComentarios(FILE* arcFinal){
    fprintf(arcFinal, "\n\n___________________________________________________________________________________________________________________________\n");
    fprintf(arcFinal, "|                                                    Lista de Comentarios                                                 |\n");
    fprintf(arcFinal, "|_________________________________________________________________________________________________________________________|\n");
    fprintf(arcFinal, "|                                                     Lexema                                           |      Token       |\n");
    fprintf(arcFinal, "|______________________________________________________________________________________________________|__________________|\n");
    imprimirCola(comentarios, arcFinal, COMENTARIO);
    
    fprintf(arcFinal, "|______________________________________________________________________________________________________|__________________|\n\n");
}


void imprimirNoReconocidos(FILE* arcFinal){
    fprintf(arcFinal, "\n\nNOTA: Asumimos que no habra cadenas no reconocidas, ya que segun las reglas pueden ser catalogadas como identificador, \n\t literal cadena, comentario o palabra reservada, por lo tanto, nos enfocamos en los caracteres que no son reconocidos.");
    fprintf(arcFinal, "\n\n_______________________________________________________________________\n");
    fprintf(arcFinal, "|         Listado de cadenas y/o caracteres NO reconocidos            |\n");
    fprintf(arcFinal, "|_____________________________________________________________________|\n");
    fprintf(arcFinal, "|                        Lexema    |    Nro de linea                  |\n");
    fprintf(arcFinal, "|__________________________________|__________________________________|\n");
    imprimirCola(NoReconocidos, arcFinal, NO_RECONOCIDOS);
    
    fprintf(arcFinal, "|__________________________________|__________________________________|\n");
}

void imprimirDirectivasPrecompilador(FILE* arcFinal){
    fprintf(arcFinal, "\n\n_______________________________________________________________________\n");
    fprintf(arcFinal, "|               Listado de directivas del Precompilador               |\n");
    fprintf(arcFinal, "|_____________________________________________________________________|\n");
    fprintf(arcFinal, "|                        Lexema    |    Nro repeticiones              |\n");
    fprintf(arcFinal, "|__________________________________|__________________________________|\n");
    fprintf(arcFinal, "|%30s\t|\t%-30d|\n", "#define", CONTADOR_DEFINE);
    fprintf(arcFinal, "|%30s\t|\t%-30d|\n", "#include", CONTADOR_INCLUDE);
    
    fprintf(arcFinal, "|__________________________________|__________________________________|");
}
